feat: Add hover info for modules and types including any docstring
fortran-lang/fortls pull request #212
Opened 2022-10-30 11:37 UTC by plevold

Fixes #208

@gnikit I decided to clone the fortls repo and have a look around. Figured I actually had a shot a making #208 work myself. Here's my suggestion. Feel free to nitpick on potential issues or anything I might have overlooked!

2022-11-01 00:40 UTC, gnikit commented
Thanks for the PR and the issue @plevold. I will try and have a look this week and leave a review. :+1:

2022-11-01 00:51 UTC, gnikit commented
The thing that you need to be extra careful is how Doxygen and modified FORD documentation can look very similar.
for example in the issue you posted you added this code

```fortran90
    !> Some documentation here?
    type :: a_t
        !> Or here?
       integer :: var    ! what if there is variable? is `!> Or here?` considered its docstrings
    end type
```

What do we expect the behaviour of the Document parser to be prefer 1 of the 2 docstrings (and if so why) or concatenate?
I remember looking into this a few years back but I don't recall what the syntax should be.

FYI
We can do **A LOT** with fortls in terms documentation. I have intentionally absteint, because users tend to get annoyed when something changes without backwards compatibility, but fortls could both auto generated docs and convert FORD to Doxygen and vice versa.

2022-11-02 07:28 UTC, plevold commented
> The thing that you need to be extra careful is how Doxygen and modified FORD documentation can look very similar.
> for example in the issue you posted you added this code

Agree and I see now that my initial issue description was incorrect in that regard. My changes actually doesn't do anything to the docstring parsing itself. The docstrings were already parsed correctly and added to the module and type objects. The only thing I had to add was to return the docstring in hover requests for module and type names.

One thing I noticed during my testing is that Doxygen style comments (aka. `pending_doc`) will get added to the next `Scope` even if there are other expressions in between. So for example, if somebody tries to add a docstring to an expression:

```fortran
subroutine sub_before
    integer :: i

    !> Trying to add a docstring to an expression
    i = 1
end subroutine


subroutine sub_no_doc
end subroutine
```

It will actually be added to the `sub_no_doc` subroutine below. I might try to fix this at some point, but I think that belongs to a separate PR.

2022-11-07 00:28 UTC, gnikit requested changes
Looks good, a couple of things are needed for this to be merged.
- rebase to master so the Markdown changes are ported
- use f-strings where possible instead of `format()` or `"str" + "val"`
- add unittests for the uncovered lines

The issue that you noted with Doxygen style comments being added to the wrong scope should also be ideally addressed since it can lead to quite a bit of a nightmare. Might be better if done in a separate PR though.

I will have some time this week after I finish the work with autocopmletions and Markdown to test your version of fortls locally and see if we need to add anything else in the hover signature and/or signature help and completions.

2022-11-07 00:28 UTC, gnikit commented on fortls/objects.py
> +        hover = "MODULE " + self.name
use fstrings and `self.get_desc`

2022-11-07 00:28 UTC, gnikit commented on fortls/objects.py
> +        return hover, long
use fstrings and consider using a list for keywords.
I think that explicit newline character might not be correct now that Markdown is being used for hover messages.

 Also, we need to provide some unit tests for the non-covered lines.

2022-11-07 00:35 UTC, gnikit commented on fortls/langserver.py
> +                hover_array.append(create_hover(hover_str, highlight))
I missed this on my review. Is this the best way for this to be done? The doc parser cannot be very robust due to their dual (FORD/Doxygen) nature so it is bound to assign incorrect documentation in multiple AST nodes. I would explicitly check of a `var_obj` is `CLASS_TYPE_ID` or `MODULE_TYPE_ID`.

Also, if it's a `SUBMODULE_TYPE_ID` how should the documentation be parsed and assigned?

2022-11-16 15:35 UTC, plevold commented
@gnikit thanks for the feedback and sorry about the delay! My schedule has been incredibly unpredictable the last month or so.

I think I now have resolved all the items you pointed out. As you noticed I also added #237 regarding the potential pitfalls with `pending_doc`.

2022-11-20 20:38 UTC, gnikit commented
There are some stuff that I need to change, style in fortran code, some changes you made that remove coverage, so if it's okay with you, I will push directly on this branch.

2022-11-20 20:59 UTC, plevold commented
Sure, no problem

2022-12-07 23:54 UTC, gnikit commented
I have no idea what's going on with the coverage reports in this PR.

I have started a new one (https://github.com/fortran-lang/fortls/pull/246) with your commit cherry-picked, but edited to undo some of the breaking changes like disabling autoupdating and `'` vs `"`. I will inspect the new coverage reports and see if any coverage lines are being removed this time around

2022-12-07 23:54 UTC, closed without merging