Issue #286: Fix wrong indentation of derived type
fortran-lang/fortls pull request #305
Opened 2023-07-09 16:34 UTC by folk85

refuse spaces in middle of derived types, add one test

2023-07-09 17:11 UTC, gnikit requested changes
Please don't change or invalidate existing tests for a modification.
None of the existing tests should have to change line numbers/column numbers.
You can add a test to demonstrate the issue that is being solved.

Also, please link to the corresponding Issue.

2023-07-09 17:13 UTC, gnikit commented
I am converting this to a draft. Please mark as ready for review when the PR is ready.

2023-07-09 18:50 UTC, folk85 commented
@gnikit , Sorry, You are right, I turn back modified tests and add new one for current Issue. As I understood it's enough just to add new commit without any additional manipulations.

2023-07-19 22:21 UTC, gnikit requested changes
Please update with relevant comments and slim down the test case, to only test the unit of code introduced.
Also update the CHANGELOG, with a matching style and descriptions as the other entries under
`Fixed`.

2023-07-19 22:21 UTC, gnikit commented on fortls/helper_functions.py
> +        # refuse any spaces in class
Comment is not accurate, the added line escapes white spaces around the access token.
I suggest the comment is removed.

2023-07-19 22:21 UTC, gnikit commented on fortls/helper_functions.py
The proposed changes will not work for arrays of derived types + whitespaces e.g.

```f90
myvar(   1  ) % foo%bar
```

The docstring of the function need to be updated to include this testcase, since the Examples are used as unit tests and contribute to coverage.

----

The modification should be in line 572:

```f90
if not line[section.start : section.end]..strip().startswith("%"):
```

2023-07-22 22:02 UTC, folk85 commented on fortls/helper_functions.py
I add test

2023-07-23 14:08 UTC, gnikit approved these changes
I updated the docstring, since they are used as unit tests.
I will merge once the checks pass.

2023-07-23 14:17 UTC, merged