Support full function-like macro expansions and allow for whitespace in PP directives
fortran-lang/fortls pull request #350
Opened 2024-01-21 03:26 UTC by emanspeaks

This is a refactor of #341 to separate out the vendor-agnostic changes.  (See earlier conversation there for some context.)

Closes #297 
Addresses spaces on either side of the hash in preprocessor lines.

Additionally, provides more robust handling of define directives as well as support for function-like macros inherited from C-style preprocessors.

2024-01-21 04:20 UTC, emanspeaks commented
Ok, I think the changes are complete.  Since this branch contains both its own contents and #350 's changes, looking at the changed files here isn't the most helpful until/unless you merge that one first.  If you want to see the Intel-specific changes relative to #350, you can look [here](https://github.com/emanspeaks/fortls/compare/generic-macro-expansions...emanspeaks:fortls:ifort-fpp-fixes)

2024-03-11 14:00 UTC, gnikit requested changes
Thank you for your efforts on this.
After review, I have a few suggestions:

- It appears there are some style changes in the diffs not essential to this PR.
  Could we revert these to maintain consistency with the original code?
- Regarding the REGEX modifications, I've observed instances of unnecessary group
  captures and alterations in expression matching that may introduce side effects.
  I recommend we take another look at these to ensure accuracy and reliability.
- I've attempted to provide a more Pythonic approach for certain additions
  to the code, aiming for clarity and conciseness.

Overall, great work. With a few adjustments based on the feedback,
I believe this will be ready for merge. Looking forward to the final touches.

2024-03-11 14:01 UTC, gnikit commented
I will have another pass at the added python code once the diffs clearup a bit.

2024-04-13 19:12 UTC, gnikit commented
I have taken the commits from this PR + the suggestions and merged them to https://github.com/fortran-lang/fortls/pull/368. The PR just got merged in master, so I am closing this. Thanks for the code @emanspeaks . I will be issuing a major release soon.

2024-04-13 19:12 UTC, closed without merging